services:
    node:
        build: .
        container_name: node
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/srv/app
            - nodes_modules:/srv/app/node_modules

volumes:
    nodes_modules:
